services:
  - type: web
    name: abuelo-por-siempre
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 